name = "multiplayer-globe-template"
main = "src/server/index.ts"
compatibility_date = "2025-04-01"
upload_source_maps = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Globe"]

[assets]
directory = "public"

[build]
command = "npx esbuild src/client/index.tsx --bundle --outdir=public/dist --splitting --sourcemap --format=esm"

[durable_objects]
bindings = [
  { name = "Globe", class_name = "Globe" }
]

[observability]
enabled = true

# Add these lines:
route = "nashsunstay.com/*"
zone_id = "37898bf39c4951e9e8ca14d0c71b3729"
